### ISSUE TITLE
BSCS v0.1

### ISSUE THREAD

**Issue by TheLubab** [curaOS/BSCS#15]
### website
- [x] #23 
- [x] #28 
- [x] #30
- [x] #32
- [x] #34
- [x] #39
- [x] https://github.com/curaOS/source/issues/219

### other packages 
- [x] add a script to deploy contract
- [x] #52
- [x] copy subgraph to packages
- [x] on deploy, automatically update contract address in all packages

## Not priority
- [ ] https://github.com/curaOS/subgraph/issues/3
- [ ] Create a frontend in `/dashboard` similar to https://www.forefront.club/dashboard with a design similar to cura.run
- [ ] Display stats from the graph in `/dashboard`
- [ ] Integrate contract with paras.id market

## Goals
- [ ] deploy a secure and tested contract to `mainnet`
- [ ] have a well-designed subgraph
